### PR TITLE
With flip_horiz, mirror output in flash rather than CSS

### LINKED ISSUE #134: in mirror mode flash permissions screen is flipped too
A minor problem: If I right-click on Flash player movie, and select Settings, I get it flipped.

flash_permissions_flipped

I am using the mirror mode (flip_horiz configuration option) because I want the camera to behave as it is in Skype.

I think it should be possible to fix this by transforming only the internal MovieClip, and not the whole flash player movie.

### PR DESCRIPTION
**Pull request by osdiab**
Closes #134.

I compiled the flash player plugin with the default Adobe Animate CC settings—namely, targeting Flash Player 16. Is that the intention? I don't know anything about Flash lol.

### CODE REVIEW

**Comment by osdiab** [comment]
@jhuckaby ping!

**Comment by osdiab** [comment]
To see it in action, you can go to http://clever.com/badges on a browser that doesn't support HTML5, like Safari. It's running my fork of webcamjs, which has this change implemented.

**Comment by jhuckaby** [comment]
Thanks for this work!  I'm sorry I haven't merged this PR yet.  I've been super busy myself, and unable to test this properly.  I'll get to this very soon!

**Comment by jhuckaby** [comment]
Seems to be working.  I don't have access to a PC with a Webcam right now, so I can't test Windows or IE.  But I merged it, so we'll see if any new support tickets come in.

**Pull request merged**
