### PR TITLE
extract parsed function

### PR DESCRIPTION
**Pull request by timsly**
Introduce `parsed` function that can be used outside upload api

### CODE REVIEW

**Comment by jhuckaby** [comment]
Sorry, I don't understand this change, and the diff looks like you changed the spacing on all my lines.

**Comment by timsly** [comment]
@jhuckaby as for spacing - that was my editor i can fix it.
As for my PR
You have `upload` method that generate Blob and than send it.
But sometimes we just need parsed Blob, so i just extracted your logic where you parse blog into `parsed` method

**Comment by jhuckaby** [comment]
Okay, thanks for the explanation.  I really don't like the name `parsed`.  It makes no sense to me, and as a user I would be confused as to what it actually did.  I'll try to implement this in a future version with another name.

**Comment by timsly** [comment]
Great. Thanks @jhuckaby

**Pull request closed without merging**
