### PR TITLE
Adding fps parameters

### LINKED ISSUE #76: Allow FPS to be configurable
We have a particular scenario where we have people using webcams over a remote connection, and the default framerate was causing the stream to eat up too much bandwidth and be somewhat unusable.

Both [Flash](http://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00000878.html) and the newest [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) both have the option to set a desired fps rate for the capture stream. You can kind of hack it in by changing the rate that webcam.js writes to a canvas object, but it's not always very responsive and it would be nice if we could use the native implementation for each.

### PR DESCRIPTION
**Pull request by scurker**
fixes #76

### CODE REVIEW

**Comment by jhuckaby** [comment]
Thanks for this, Jason!  Unfortunately it looks like your text editor has done something crazy to all my files.  It looks like all the spacing in the blank lines has been changed, so the diff is totally unreadable.  But I understand the gist of the change, and I'll implement it by hand if I have to.  Thanks again!

**Comment by eagunn** [comment]
Joseph, you and Jason are probably suffering from a simple case of line
ending confusion.

Most diff tools have an 'ignore whitespace' or 'ignore unimportant changes'
option. Don't know if you can force this on github or not but for
commandline git, there's
git diff -w

ag

On Fri, May 8, 2015 at 3:41 PM, Joseph Huckaby <notifications@github.com>
wrote:

> Thanks for this, Jason! Unfortunately it looks like your text editor has
> done something crazy to all my files. It looks like all the spacing in the
> blank lines has been changed, so the diff is totally unreadable. But I
> understand the gist of the change, and I'll implement it by hand if I have
> to. Thanks again!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhuckaby/webcamjs/pull/77#issuecomment-100375842>.
>



-- 
Anne Gunn, Founder
Sheridan Programmers Guild
307 673 5234

**Comment by scurker** [comment]
@jhuckaby The editor I uses strips extra whitespaces and I didn't realize it was different because I usually ignore whitespaces when I do comparisons. I can update the pull request to restore your line endings sometime tomorrow if that would help.

But a quick tip: If you add `&w=1` to the github comparison url, it'll ignore whitespaces for the comparisons.

**Comment by scurker** [comment]
@jhuckaby Everything has been updated with all the whitespace changes ignored

**Comment by jhuckaby** [comment]
Thanks Jason!  Awesome PR!  Merged.

**Comment by jhuckaby** [comment]
Unfortunately, this has broken WebcamJS on Chrome on Mac:

`Uncaught TypeError: Failed to execute 'webkitGetUserMedia' on 'Navigator': Malformed constraints object.`

It doesn't like your new FPS constraints object.  I'll have to comment it out for now.

**Comment by scurker** [comment]
That's fine, the spec isn't finalized yet and currently only works in Firefox. I didn't realize Chrome would break with the constraints object - but I'm sure it's not too far down the pipeline.

**Comment by jhuckaby** [comment]
Ah I see, this is a Firefox thing.  Cool.  I could do a browser detect, but I'd rather wait until Chrome comes on board, as it's cleaner.

**Pull request merged**
